### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by 43998213** [Kingzhoudk/JLing#3]
I got this 

/Users/apple/Desktop/ZWWDVersion3V3.1/venv/bin/python /Users/apple/Desktop/JLing/JLing.py
Traceback (most recent call last):
  File "/Users/apple/Desktop/JLing/Snowboy/snowboydetect.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Snowboy._snowboydetect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Desktop/JLing/JLing.py", line 2, in <module>
    from Speak import JLing_Speak
  File "/Users/apple/Desktop/JLing/Speak.py", line 11, in <module>
    from Snowboy.snowboy import Snowboy_JLing
  File "/Users/apple/Desktop/JLing/Snowboy/snowboy.py", line 2, in <module>
    from . import snowboydecoder
  File "/Users/apple/Desktop/JLing/Snowboy/snowboydecoder.py", line 6, in <module>
    from . import snowboydetect
  File "/Users/apple/Desktop/JLing/Snowboy/snowboydetect.py", line 17, in <module>
    _snowboydetect = swig_import_helper()
  File "/Users/apple/Desktop/JLing/Snowboy/snowboydetect.py", line 16, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_snowboydetect'

**Comment by Kingzhoudk** [comment]
没有安装插件: snowboy ?

**Comment by Kingzhoudk** [comment]
https://blog.csdn.net/weixin_40490238/article/details/102300225

**Comment by 43998213** [comment]
> https://blog.csdn.net/weixin_40490238/article/details/102300225
刚看到，已经解决了，是这个问题，非常感谢。
